# Generated by Django 4.2.6 on 2023-10-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_duvidas_respostas_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='duvidas',
            name='arquivo',
            field=models.FileField(blank=None, default=None, null=None, upload_to='uploads/%Y/%m/%d/', verbose_name='Arquivo'),
        ),
    ]
