# Generated by Django 4.2.6 on 2023-10-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_alter_comentarios_data_alter_duvidas_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duvidas',
            name='arquivo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Arquivo'),
        ),
    ]
