# Generated by Django 4.2.6 on 2023-11-01 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0007_comentarios_visibilidade_duvidas_visibilidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostas',
            name='duvida',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.duvidas', verbose_name='Dúvida'),
        ),
        migrations.CreateModel(
            name='RecuperacaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=2000, verbose_name='Código')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('recuperacao', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('reject', 'reject')], default='', max_length=30, verbose_name='Foi feita a recuperação?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Recuperação de Senha',
                'verbose_name_plural': 'Recuperação de Senhas',
            },
        ),
    ]
