# Generated by Django 4.2.6 on 2023-11-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_alter_respostas_duvida_recuperacaosenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='verificacao_email',
            field=models.BooleanField(default=False, verbose_name='Verificou o E-mail?'),
        ),
        migrations.AlterField(
            model_name='recuperacaosenha',
            name='recuperacao',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('reject', 'reject')], default='pending', max_length=30, verbose_name='Foi feita a recuperação?'),
        ),
    ]
