# Generated by Django 4.2.6 on 2023-11-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_perfil_codigo_perfil_verificacao_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duvidas',
            name='arquivo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='duvidas/%Y/%m/%d/', verbose_name='Arquivo'),
        ),
    ]
