# Generated by Django 4.2.6 on 2023-10-18 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0005_alter_curso_nome_alter_modulo_nome_alter_video_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiberacaoModulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liberacao', models.BooleanField(default=True, verbose_name='Liberação')),
                ('modulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cursos.modulo', verbose_name='Curso')),
                ('usuario', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Liberação do Módulo',
                'verbose_name_plural': 'Liberação dos Módulos',
            },
        ),
        migrations.CreateModel(
            name='LiberacaoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liberacao', models.BooleanField(default=True, verbose_name='Liberação')),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso', verbose_name='Curso')),
                ('usuario', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Liberação do Curso',
                'verbose_name_plural': 'Liberação dos Cursos',
            },
        ),
    ]
