# Generated by Django 4.2.6 on 2023-10-18 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0006_alter_modulo_curso_alter_video_modulo'),
        ('liberacao', '0002_alter_liberacaomodulos_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberacaomodulos',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.modulo', verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='liberacaomodulos',
            name='usuario',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.DeleteModel(
            name='LiberacaoCurso',
        ),
    ]
