# Generated by Django 4.2.6 on 2023-10-18 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_alter_modulo_curso_alter_video_modulo'),
        ('liberacao', '0003_alter_liberacaomodulos_modulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberacaomodulos',
            name='curso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso', verbose_name='Curso'),
        ),
    ]
