# Generated by Django 4.2.6 on 2023-10-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liberacao', '0004_liberacaomodulos_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liberacaomodulos',
            name='curso',
        ),
    ]
