# Generated by Django 4.2.6 on 2023-11-05 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0014_video_arquivo'),
        ('liberacao', '0005_remove_liberacaomodulos_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiberacaoVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liberacao', models.BooleanField(default=True, verbose_name='Liberação')),
                ('usuario', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.video', verbose_name='Vídeo')),
            ],
            options={
                'verbose_name': 'Liberação do Vídeo',
                'verbose_name_plural': 'Liberação dos Vídeos',
            },
        ),
    ]
