# Generated by Django 4.2.6 on 2023-11-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberacao', '0008_liberacaogradual_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liberacaovideos',
            name='tempo',
        ),
        migrations.AddField(
            model_name='liberacaogradual',
            name='tempo',
            field=models.CharField(choices=[('Diário', 'Diário'), ('Semanal', 'Semanal'), ('Mensal', 'Mensal')], default='Diário', max_length=30, verbose_name='Tempo de Liberação'),
        ),
    ]
