# Generated by Django 4.2.6 on 2023-11-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberacao', '0009_remove_liberacaovideos_tempo_liberacaogradual_tempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liberacaogradual',
            name='videos_liberados',
        ),
        migrations.AddField(
            model_name='liberacaogradual',
            name='periodo_liberado',
            field=models.CharField(default='', max_length=40000, verbose_name='Número de Vídeos Liberados'),
        ),
    ]
