# Generated by Django 4.2.6 on 2023-11-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberacao', '0010_remove_liberacaogradual_videos_liberados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberacaogradual',
            name='periodo_liberado',
            field=models.CharField(blank=True, default='', max_length=40000, null=True, verbose_name='Número de Vídeos Liberados'),
        ),
    ]
