# Generated by Django 4.2.6 on 2023-11-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberacao', '0011_alter_liberacaogradual_periodo_liberado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liberacaogradual',
            name='periodo_liberado',
        ),
        migrations.AddField(
            model_name='liberacaogradual',
            name='diferenca_periodo',
            field=models.IntegerField(default=0, verbose_name='Diferença Período'),
        ),
        migrations.AddField(
            model_name='liberacaogradual',
            name='videos_liberados',
            field=models.IntegerField(default=0, verbose_name='Número de Vídeos Liberados'),
        ),
    ]
