# Generated by Django 4.2.7 on 2023-12-06 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_alter_video_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liberacao', '0012_remove_liberacaogradual_periodo_liberado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberacaogradual',
            name='tempo',
            field=models.CharField(choices=[('Diário', 'Diário'), ('Dois Dias', 'Dois Dias'), ('Semanal', 'Semanal')], default='Diário', max_length=30, verbose_name='Tempo de Liberação'),
        ),
        migrations.CreateModel(
            name='LiberacaoTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso', verbose_name='Curso')),
                ('usuario', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Liberação Total',
                'verbose_name_plural': 'Liberação Total',
            },
        ),
    ]
