# Generated by Django 4.2.6 on 2023-10-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='visibilidade',
            field=models.BooleanField(default=True, verbose_name='Visibilidade'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='visibilidade',
            field=models.BooleanField(default=True, verbose_name='Visibilidade'),
        ),
        migrations.AddField(
            model_name='video',
            name='visibilidade',
            field=models.BooleanField(default=True, verbose_name='Visibilidade'),
        ),
        migrations.AlterField(
            model_name='video',
            name='descricao',
            field=models.TextField(default='', max_length=10000, verbose_name='Descrição'),
        ),
    ]
