# Generated by Django 4.2.6 on 2023-10-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_visibilidade_modulo_visibilidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/%Y/%m/%d', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='modulos/%Y/%m/%d', verbose_name='Foto'),
        ),
    ]
