# Generated by Django 4.2.6 on 2023-10-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_foto_modulo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.SlugField(default='', max_length=1500, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nome',
            field=models.SlugField(default='', max_length=1500, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='video',
            name='nome',
            field=models.SlugField(default='', max_length=1500, verbose_name='Nome'),
        ),
    ]
