# Generated by Django 4.2.6 on 2023-10-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_curso_nome_alter_modulo_nome_alter_video_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.SlugField(default='', max_length=1500, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nome',
            field=models.SlugField(default='', max_length=1500, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='video',
            name='nome',
            field=models.SlugField(default='', max_length=1500, unique=True, verbose_name='Nome'),
        ),
    ]
