# Generated by Django 4.2.6 on 2023-10-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_curso_nome_alter_modulo_nome_alter_video_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='video',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.modulo', verbose_name='Módulo'),
        ),
    ]
