# Generated by Django 4.2.6 on 2023-10-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_alter_modulo_curso_alter_video_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='ordem',
            field=models.IntegerField(default=1, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='video',
            name='ordem',
            field=models.IntegerField(default=1, verbose_name='Ordem'),
        ),
    ]
