# Generated by Django 4.2.6 on 2023-10-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_alter_modulo_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='curso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso', verbose_name='Curso'),
        ),
    ]
