# Generated by Django 4.2.6 on 2023-11-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_marcarvistovideo_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='arquivo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='arquivos_videos/%Y/%m/%d/', verbose_name='Arquivo'),
        ),
    ]
