# Generated by Django 4.2.7 on 2023-11-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_video_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(blank=True, default=None, max_length=2000, null=True, verbose_name='Link'),
        ),
    ]
